-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Latte.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Latte.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Latte.Abs.Ident -> Result
transIdent x = case x of
  Latte.Abs.Ident string -> failure x

transProgram :: Show a => Latte.Abs.Program' a -> Result
transProgram x = case x of
  Latte.Abs.Prog _ stmts -> failure x

transStmt :: Show a => Latte.Abs.Stmt' a -> Result
transStmt x = case x of
  Latte.Abs.SAss _ ident exp -> failure x
  Latte.Abs.SExp _ exp -> failure x

transExp :: Show a => Latte.Abs.Exp' a -> Result
transExp x = case x of
  Latte.Abs.ExpAdd _ exp1 exp2 -> failure x
  Latte.Abs.ExpSub _ exp1 exp2 -> failure x
  Latte.Abs.ExpMul _ exp1 exp2 -> failure x
  Latte.Abs.ExpDiv _ exp1 exp2 -> failure x
  Latte.Abs.ExpLit _ integer -> failure x
  Latte.Abs.ExpVar _ ident -> failure x
